module.exports.genus = [
    'Abelia',
    'Abeliophyllum',
    'Abelmoschus',
    'Abies',
    'Abronia',
    'Abutilon',
    'Acacia',
    'Acaena',
    'Acalypha',
    'Acantholimon',
    'Acanthus',
    'Acca',
    'Acer',
    'Achillea',
    'Achimenes',
    'Acinos',
    'Aciphylla',
    'Acis',
    'Acmella',
    'Acmena',
    'Aconitum',
    'Acorus',
    'Actaea',
    'Actinidia',
    'Actinotus'
]

module.exports.species = [
    'Orange Eye',
    'capensis',
    'ovata',
    'furfuracea',
    'nesophila',
    'pumila',
    'zamiifolia',
    'Allure',
    'Amethyst',
    'Black Magic',
    'Cameo',
    'Cancun',
    'Cantor',
    'Branco', 
    'Marrero',
    'Murano',
    'Promise', 
    'Reno', 
    'Romance', 
    'Rosette', 
    'Safari', 
    'Trinity', 
    'Crystal Blush',
    'Dubai Nights',
    'Edge of Night'
]